import { supabase, requireSession, esc } from '../shared/portal-shell.js';
await requireSession({admin:true});
let people=[],slots=[],current=null; const rows=document.getElementById('rows'),search=document.getElementById('search'),dlg=document.getElementById('edit'),form=document.getElementById('edit-form');
async function load(){const [a,s]=await Promise.all([supabase.rpc('get_admin_accounts'),supabase.from('orbat_slots').select('callsign,default_role').eq('active',true).order('sort_order')]);if(a.error)throw a.error;if(s.error)throw s.error;people=a.data||[];slots=s.data||[];render()}
function rank(p){return p.branch==='Navy'?p.navy_rank:p.branch==='Army'?p.army_rank:p.branch==='Air Force'?p.air_force_rank:''}
function render(){const q=search.value.toLowerCase();rows.innerHTML='';for(const p of people.filter(x=>JSON.stringify(x).toLowerCase().includes(q))){const tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc([p.fictional_first_name,p.fictional_last_name].filter(Boolean).join(' ')||'Unnamed')}</b><br><span class="muted">${esc(p.email)}</span></td><td>${esc(p.callsign||'—')}</td><td>${esc(p.branch||'—')}<br><span class="muted">${esc(rank(p)||'Unassigned')}</span></td><td>${esc(p.team||'—')}<br><span class="muted">${esc(p.billet||'—')}</span></td><td>${esc(p.leadership_level)}</td><td><span class="status ${esc(p.account_status)}">${esc(p.account_status)}</span></td><td><button class="button">Edit</button></td>`;tr.querySelector('button').onclick=()=>openEdit(p);rows.appendChild(tr)}}
function openEdit(p){current=p;const f=form.elements;f.first.value=p.fictional_first_name||'';f.last.value=p.fictional_last_name||'';f.callsign.innerHTML='<option value="">Unassigned</option>'+slots.map(s=>`<option value="${esc(s.callsign)}">${esc(s.callsign)} — ${esc(s.default_role)}</option>`).join('');f.callsign.value=p.callsign||'';f.branch.value=p.branch||'';f.navy_rank.value=p.navy_rank||'';f.army_rank.value=p.army_rank||'';f.air_force_rank.value=p.air_force_rank||'';f.billet.value=p.billet||'';f.position_title.value=p.position_title||'';f.team.value=p.team||'';f.squadron.value=p.squadron||'';f.troop.value=p.troop||'';f.leadership.value=p.leadership_level||'Member';f.status.value=p.account_status||'active';f.admin.checked=!!p.is_admin;f.cadre.checked=!!p.is_cadre;f.candidate.checked=!!p.is_candidate;document.getElementById('message').textContent='';dlg.showModal()}
form.onsubmit=async e=>{e.preventDefault();const f=form.elements;const args={p_id:current.id,p_first_name:f.first.value,p_last_name:f.last.value,p_callsign:f.callsign.value||null,p_branch:f.branch.value||null,p_navy_rank:f.navy_rank.value,p_army_rank:f.army_rank.value,p_air_force_rank:f.air_force_rank.value,p_billet:f.billet.value,p_team:f.team.value,p_squadron:f.squadron.value,p_troop:f.troop.value,p_leadership_level:f.leadership.value,p_is_admin:f.admin.checked,p_is_cadre:f.cadre.checked,p_is_candidate:f.candidate.checked,p_account_status:f.status.value,p_position_title:f.position_title.value};const {error}=await supabase.rpc('admin_update_account',args);if(error){document.getElementById('message').textContent=error.message;return}dlg.close();await load()};
document.getElementById('cancel').onclick=()=>dlg.close();search.oninput=render;await load();
