import { supabase, requireSession, displayName, formatDateTime, esc } from '../shared/portal-shell.js';
const {account}=await requireSession();const candidate=account.is_candidate||String(account.email).toLowerCase().endsWith('@candidate.mil');const {data:isInstructor}=await supabase.rpc('portal_is_instructor',{p_user:account.id});let sessions=[],responses=[],people=[],tentativeSession=null,current=null;
const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local';document.getElementById('tz').textContent=tz;
if(!candidate)document.getElementById('new-session').hidden=false;
const form=document.getElementById('session-form'),dlg=document.getElementById('session-dialog');
function sessionTypes(){return isInstructor?['Green Team','Pro Development','Official Training']:['Pro Development']}
function typeOptions(selected=''){return sessionTypes().map(x=>`<option${x===selected?' selected':''}>${esc(x)}</option>`).join('')}
function localValue(iso){if(!iso)return'';const d=new Date(iso),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
async function load(){const [s,p]=await Promise.all([supabase.from('training_sessions').select('*').order('starts_at',{ascending:true}),supabase.rpc('get_portal_people')]);if(s.error)throw s.error;if(p.error)throw p.error;sessions=s.data||[];people=p.data||[];responses=[];if(sessions.length){const r=await supabase.from('session_responses').select('*').in('session_id',sessions.map(x=>x.id));if(!r.error)responses=r.data||[]}render()}
function hostName(id){const p=people.find(x=>x.id===id);return p?`${displayName(p)}${p.callsign?` / ${p.callsign}`:''}`:'Unknown'}
function myResponse(id){return responses.find(r=>r.session_id===id&&r.user_id===account.id)}
async function canManage(id){const {data}=await supabase.rpc('portal_can_manage_session',{p_session:id,p_user:account.id});return!!data}
function render(){const root=document.getElementById('sessions');root.replaceChildren();document.getElementById('list-status').textContent=`${sessions.length} visible session${sessions.length===1?'':'s'}`;for(const s of sessions){const mine=myResponse(s.id),node=document.createElement('article');node.className='session';node.innerHTML=`<div class="session-head"><div><h3>${esc(s.title)}</h3><span class="muted">Hosted by ${esc(hostName(s.created_by))}</span><div class="chips"><span class="status">${esc(s.session_type)}</span><span class="status">${esc(s.location)}</span><span class="status ${esc(s.status)}">${esc(s.status)}</span></div></div><div class="session-meta"><b>${esc(formatDateTime(s.starts_at))}</b><br>${esc(tz)}</div></div><div class="session-body"><div>${esc(s.description||'No description provided.')}</div><div class="rsvp"><button class="button ${mine?.response==='attending'?'selected':''}" data-r="attending">Attending</button><button class="button ${mine?.response==='not_attending'?'selected':''}" data-r="not_attending">Not Attending</button><button class="button ${mine?.response==='tentative'?'selected':''}" data-r="tentative">Tentative</button></div>${mine?.tentative_reason?`<div class="notice" style="margin-top:8px">Tentative reason: ${esc(mine.tentative_reason)}</div>`:''}${s.aar?`<div class="host-tools"><b>AAR</b><br><span class="muted">${esc(s.aar)}</span></div>`:''}<div class="host-tools actions" data-tools hidden><button class="button" data-edit>Edit / AAR</button><button class="button primary" data-complete>Mark Completed</button></div></div>`;
node.querySelectorAll('[data-r]').forEach(b=>b.onclick=e=>{e.preventDefault();respond(s,b.dataset.r)});canManage(s.id).then(ok=>{if(ok){node.querySelector('[data-tools]').hidden=false;node.querySelector('[data-edit]').onclick=()=>openEdit(s);node.querySelector('[data-complete]').onclick=()=>complete(s)}});root.appendChild(node)}}
async function respond(s,response){if(response==='tentative'){tentativeSession=s;document.getElementById('tentative-form').reset();document.getElementById('tentative-dialog').showModal();return}const payload={session_id:s.id,user_id:account.id,response,tentative_reason:null,responded_at:new Date().toISOString()};const {error}=await supabase.from('session_responses').upsert(payload);if(error)alert(error.message);else load()}
document.getElementById('tentative-form').onsubmit=async e=>{e.preventDefault();const reason=e.currentTarget.elements.reason.value.trim();const {error}=await supabase.from('session_responses').upsert({session_id:tentativeSession.id,user_id:account.id,response:'tentative',tentative_reason:reason,responded_at:new Date().toISOString()});if(error){document.getElementById('tentative-error').textContent=error.message;return}document.getElementById('tentative-dialog').close();load()};document.getElementById('tentative-cancel').onclick=()=>document.getElementById('tentative-dialog').close();
function openNew(){current=null;form.reset();form.elements.id.value='';form.elements.type.innerHTML=typeOptions();form.elements.location.value='Undecided';form.elements.aar.disabled=true;document.getElementById('delete-session').hidden=true;document.getElementById('session-error').textContent='';dlg.showModal()}
function openEdit(s){current=s;form.elements.id.value=s.id;form.elements.title.value=s.title;form.elements.type.innerHTML=typeOptions(s.session_type);if(!sessionTypes().includes(s.session_type))form.elements.type.innerHTML+=`<option selected>${esc(s.session_type)}</option>`;form.elements.starts.value=localValue(s.starts_at);form.elements.location.value=s.location;form.elements.description.value=s.description||'';form.elements.aar.value=s.aar||'';form.elements.aar.disabled=false;document.getElementById('delete-session').hidden=false;document.getElementById('session-error').textContent='';dlg.showModal()}
document.getElementById('new-session').onclick=openNew;document.getElementById('close-session').onclick=()=>dlg.close();form.onsubmit=async e=>{e.preventDefault();const f=form.elements,payload={title:f.title.value.trim(),session_type:f.type.value,starts_at:new Date(f.starts.value).toISOString(),location:f.location.value,description:f.description.value.trim(),aar:f.aar.disabled?'':f.aar.value.trim(),updated_at:new Date().toISOString()};let result;if(current)result=await supabase.from('training_sessions').update(payload).eq('id',current.id);else result=await supabase.from('training_sessions').insert({...payload,created_by:account.id});if(result.error){document.getElementById('session-error').textContent=result.error.message;return}dlg.close();load()};
async function complete(s){if(!confirm(`Mark ${s.title} as completed?`))return;const {error}=await supabase.from('training_sessions').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',s.id);if(error)alert(error.message);else load()}
document.getElementById('delete-session').onclick=async()=>{if(!current||!confirm('Permanently remove this session?'))return;const {error}=await supabase.from('training_sessions').delete().eq('id',current.id);if(error)document.getElementById('session-error').textContent=error.message;else{dlg.close();load()}};await load();
